### ISSUE TITLE
Not compatible with mher/flower:latest (v 1.0)

### ISSUE THREAD

**Issue by kyleflan** [tiangolo/uvicorn-gunicorn-fastapi-docker#102]
Version 1.0 of [mher/flower](https://hub.docker.com/layers/mher/flower/latest/images/sha256-bd388a00438d3dbe836196e7d0491527db7ccb5f07fc1b3afc33016311fc283a?context=explore) breaks docker compose for this project. See this [issue](https://github.com/mher/flower/issues/1122) at mher/flower for details related to the change from 0.9.7 -> 1.0.0.

Workaround 1:

Modify the image in `docker-compose.yml` to use the `0.9.7` tag:

```yaml
  flower:
    image: mher/flower:0.9.7
    networks:
```
Workaround 2:

Update `docker-compose.yml` to work properly with the latest version of mher/flower:

```yaml
  flower:
    image: mher/flower
    networks:
      - ${TRAEFIK_PUBLIC_NETWORK?Variable not set}
      - default
    env_file:
      - .env
    command:
      - "celery"
      - "--broker=amqp://guest@queue:5672//"
      - "flower"
```

Examples of `docker run` between the two versions:

```sh
$ docker run mher/flower:latest "--broker=amqp://guest@queue:5672//"
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "--broker=amqp://guest@queue:5672//": stat --broker=amqp://guest@queue:5672//: no such file or directory: unknown.
ERRO[0000] error waiting for container: context canceled 
```
vs
```sh
$ docker run mher/flower:0.9.7 "--broker=amqp://guest@queue:5672//"
[I 210816 19:48:14 command:135] Visit me at http://localhost:5555
[I 210816 19:48:14 command:142] Broker: amqp://guest:**@queue:5672//
[I 210816 19:48:14 command:143] Registered tasks: 
    ['celery.accumulate',
     'celery.backend_cleanup',
     'celery.chain',
     'celery.chord',
     'celery.chord_unlock',
     'celery.chunks',
     'celery.group',
     'celery.map',
     'celery.starmap']
```
