### ISSUE TITLE
unable to find additional script /start-reload.sh

### ISSUE THREAD

**Issue by tridelt** [tiangolo/uvicorn-gunicorn-fastapi-docker#103]
Dear team,

thank you for this awesome repo.
For development, the docs mention  the ```/start-reload.sh```. However I cannot find it here. Where could it be?

Yours
Tridelt

**Comment by tridelt** [comment]
#Solved 

It is embedded in a lower layer ALREADY EMBEDDED inside the image.

Thank you! : ) Awesome repo!

**Comment by razzeee** [comment]
Could you post how you solved this?

**Comment by tridelt** [comment]
@razzeee 
for instance you could put this into your dockerfile
```
version: '3'
services:
  web:
    build: ./
    command: /start-reload.sh
    volumes:
      - ./app:/app
    ports:
      - "8080:80"
```
