### ISSUE TITLE
Only one CPU is being used on 4 core CPU

### ISSUE THREAD

**Issue by laxmimerit** [tiangolo/uvicorn-gunicorn-fastapi-docker#57]
Hi,
I am hosting a web application on 4 cores CPU. When I make concurrent requests, only one CPU is being used and other 3 CPU's are using only 3 to 4%. How can I get high parallelism and concurrency?

my `docker-compose` file is as follows
```
version: '3'
services:
  web:
    build:
      context: .
      
    volumes:
      - ./app:/app
    ports:
      - "80:80"
    environment:
      - WORKERS=16

    command: bash -c "uvicorn main:app --reload --host 0.0.0.0 --port 80"
```

I have tried to set `WORKERS` but it is not getting reflected. Only one CPU is being used regardless of `WORKERS` value.
How can I correctly set these values?
